trigger:
  branches:
    include:
      - main

variables:
  fixVersion: '1.0.0'  # Set dynamically via pipeline variables or parameters

stages:
  - stage: ReleaseBranch
    displayName: "Create/Update Release Branch"
    jobs:
      - job: CreateReleaseBranch
        displayName: "Create or Update Release Branch for FixVersion"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true  # <-- allows $(System.AccessToken) to be used

          - task: PowerShell@2
            displayName: "Create/Update Release Branch"
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                $fixVersion = "${{ variables.fixVersion }}"
                Write-Host "🚀 Starting release branch update for FixVersion: $fixVersion"

                # --- CONFIG ---
                $orgUrl = "https://dev.azure.com/pradeepekka"
                $project = "Algo-ds-Py"
                $repo = "algo-ds-py"
                $releaseBranch = "release/$fixVersion"
                $token = "$(System.AccessToken)"
                $headers = @{ Authorization = "Bearer $token" }

                # --- STEP 1: Fetch work items ---
                Write-Host "🔍 Fetching work items with FixVersion = $fixVersion..."
                $wiql = @{
                  query = "SELECT [System.Id] FROM WorkItems WHERE [System.TeamProject] = '$project' AND [Custom.FixVersion] = '$fixVersion'"
                } | ConvertTo-Json

                $wiqlUrl = "$orgUrl/$project/_apis/wit/wiql?api-version=7.0"
                try {
                  $wiqlResult = Invoke-RestMethod -Uri $wiqlUrl -Method Post -Headers $headers -Body $wiql -ContentType "application/json"
                } catch {
                  Write-Host "❌ Failed to fetch work items: $($_.Exception.Message)"
                  exit 1
                }

                if (-not $wiqlResult.workItems) {
                    Write-Host "⚠️ No work items found for FixVersion $fixVersion"
                    exit 0
                }

                # --- STEP 2: Process work items ---
                $finalWorkItems = @()

                foreach ($wi in $wiqlResult.workItems) {
                    $wiId = $wi.id
                    $relationsUrl = "$orgUrl/$project/_apis/wit/workitems/$wiId?`$expand=relations&api-version=7.0"

                    try {
                        $wiDetails = Invoke-RestMethod -Uri $relationsUrl -Headers $headers
                        $prLinks = $wiDetails.relations | Where-Object { $_.rel -eq "ArtifactLink" -and $_.url -like "*PullRequest*" }

                        if (-not $prLinks) {
                            Write-Host "⚠️ Work item #$wiId has no linked PRs. Skipping..."
                            continue
                        }

                        $allApproved = $true
                        foreach ($prLink in $prLinks) {
                            if ($prLink.url -match "vstfs:///Git/PullRequestId/(\d+)") {
                                $prId = $matches[1]
                                $prApiUrl = "$orgUrl/$project/_apis/git/repositories/$repo/pullRequests/$prId?api-version=7.0"
                                $pr = Invoke-RestMethod -Uri $prApiUrl -Headers $headers

                                if ($pr.status -ne "completed" -or $pr.mergeStatus -ne "succeeded") {
                                    Write-Host "❌ PR #$prId for Work Item #$wiId is not approved or merged yet."
                                    $allApproved = $false
                                    break
                                }
                            }
                        }

                        if ($allApproved) {
                            Write-Host "✅ Work Item #$wiId has all PRs approved."
                            $finalWorkItems += $wiId
                        } else {
                            Write-Host "🚫 Skipping Work Item #$wiId because not all PRs approved."
                        }

                    } catch {
                        Write-Host "❌ Failed to fetch Work Item #$wiId: $($_.Exception.Message)"
                    }
                }

                if (-not $finalWorkItems) {
                    Write-Host "⚠️ No work items qualify for release."
                    exit 0
                }

                # --- STEP 3: Prepare release branch ---
                Write-Host "🔧 Preparing release branch: $releaseBranch"

                git fetch origin
                $branchExists = (git branch -r | Select-String "origin/$releaseBranch")

                if ($branchExists) {
                    Write-Host "📦 Release branch exists. Updating..."
                    git checkout $releaseBranch
                    git pull origin $releaseBranch
                } else {
                    Write-Host "🌱 Creating new release branch from main..."
                    git checkout main
                    git pull origin main
                    git checkout -b $releaseBranch
                }

                # --- STEP 4: Merge approved PR commits ---
                foreach ($wiId in $finalWorkItems) {
                    Write-Host "🔗 Processing PRs for Work Item #$wiId..."
                    $relationsUrl = "$orgUrl/$project/_apis/wit/workitems/$wiId?`$expand=relations&api-version=7.0"
                    $wiDetails = Invoke-RestMethod -Uri $relationsUrl -Headers $headers
                    $prLinks = $wiDetails.relations | Where-Object { $_.rel -eq "ArtifactLink" -and $_.url -like "*PullRequest*" }

                    foreach ($prLink in $prLinks) {
                        if ($prLink.url -match "vstfs:///Git/PullRequestId/(\d+)") {
                            $prId = $matches[1]
                            $prApiUrl = "$orgUrl/$project/_apis/git/repositories/$repo/pullRequests/$prId?api-version=7.0"
                            $pr = Invoke-RestMethod -Uri $prApiUrl -Headers $headers

                            if ($pr.status -eq "completed" -and $pr.mergeStatus -eq "succeeded") {
                                $sourceBranch = $pr.sourceRefName.Replace("refs/heads/", "")
                                Write-Host "🔀 Merging commits from branch: $sourceBranch"
                                git fetch origin $sourceBranch
                                git merge origin/$sourceBranch --no-edit
                            }
                        }
                    }
                }

                git push origin $releaseBranch
                Write-Host "🎉 Release branch $releaseBranch updated successfully."
