trigger:
  branches:
    include:
      - main

variables:
  fixVersion: '1.0.0'

stages:
  - stage: ReleaseBranch
    displayName: "Create/Update Release Branch with Cherry-Picked Commits"
    jobs:
      - job: CreateReleaseBranch
        displayName: "Create or Update Release Branch for FixVersion"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true

          - task: PowerShell@2
            displayName: "Create/Update Release Branch with Cherry-Picked Commits"
            inputs:
              targetType: 'inline'
              pwsh: true
              script: |
                # Assign fixVersion from pipeline variable
                $fixVersion = "${{ variables.fixVersion }}"
                Write-Host "🚀 Starting release branch update for FixVersion: ${fixVersion}"

                # Configuration
                $orgUrl = "https://pradeepekka.visualstudio.com"
                $project = "Algo-ds-Py"
                $repo = "algo-ds-py"
                $releaseBranch = "release/${fixVersion}"
                $token = "$(System.AccessToken)"
                $headers = @{
                  Authorization = "Bearer $token"
                  "Content-Type" = "application/json"
                }

                # Step 1: Fetch work items by WIQL
                Write-Host "##[section]🔍 Fetching work items for FixVersion = ${fixVersion}"
                $wiql = @{
                  query = "SELECT [System.Id] FROM WorkItems WHERE [System.TeamProject] = '$project' AND [Custom.FixVersion] = '$fixVersion'"
                } | ConvertTo-Json

                $wiqlUrl = "$orgUrl/$project/_apis/wit/wiql?api-version=7.0"
                try {
                  $wiqlResult = Invoke-RestMethod -Uri $wiqlUrl -Method Post -Headers $headers -Body $wiql
                } catch {
                  Write-Host "##[error]Failed to fetch work items: $($_.Exception.Message)"
                  exit 1
                }

                if (-not $wiqlResult.workItems -or $wiqlResult.workItems.Count -eq 0) {
                  Write-Host "⚠️ No work items found for FixVersion '${fixVersion}'"
                  exit 0
                }

                # Step 2: Process each work item, collect merge commits
                $qualifiedWorkItems = @()
                $cherryPickCommits = @()

                foreach ($wi in $wiqlResult.workItems) {
                  $wiId = $wi.id
                  Write-Host "##[section]Processing Work Item #${wiId}..."

                  $wiUrl = "$orgUrl/$project/_apis/wit/workitems/$wiId?%24expand=relations&api-version=7.0"
                  try {
                    $wiDetails = Invoke-RestMethod -Uri $wiUrl -Headers $headers
                  } catch {
                    Write-Host "##[error]Failed to fetch Work Item #${wiId}: $($_.Exception.Message)"
                    continue
                  }

                  $prLinks = @()
                  if ($wiDetails.relations) {
                    $prLinks = $wiDetails.relations | Where-Object {
                      $_.rel -eq "ArtifactLink" -and $_.url -like "*PullRequest*"
                    }
                  }

                  if (-not $prLinks -or $prLinks.Count -eq 0) {
                    Write-Host "⚠️ Work Item #${wiId} has no linked PRs. Skipping."
                    continue
                  }

                  $allApproved = $true

                  foreach ($prLink in $prLinks) {
                    if ($prLink.url -match "vstfs:///Git/PullRequestId/(\d+)") {
                      $prId = $matches[1]
                      Write-Host "🔗 Checking PR #${prId}..."

                      $prUrl = "$orgUrl/$project/_apis/git/repositories/$repo/pullRequests/$prId?api-version=7.0"
                      try {
                        $pr = Invoke-RestMethod -Uri $prUrl -Headers $headers

                        if ($pr.status -eq "completed" -and $pr.mergeStatus -eq "succeeded") {
                          $mergeCommit = $pr.lastMergeCommit.commitId
                          Write-Host "✅ PR #${prId} merged; commit ${mergeCommit}"
                          $cherryPickCommits += $mergeCommit
                        } else {
                          Write-Host "🚫 PR #${prId} not merged or incomplete"
                          $allApproved = $false
                          break
                        }
                      } catch {
                        Write-Host "##[error]Failed to fetch PR #${prId}: $($_.Exception.Message)"
                        $allApproved = $false
                        break
                      }
                    }
                  }

                  if ($allApproved) {
                    Write-Host "✅ Work Item #${wiId} qualifies"
                    $qualifiedWorkItems += $wiId
                  } else {
                    Write-Host "🚫 Work Item #${wiId} disqualified"
                  }
                }

                if (-not $qualifiedWorkItems -or $qualifiedWorkItems.Count -eq 0) {
                  Write-Host "⚠️ No qualified work items"
                  exit 0
                }

                Write-Host "🎯 Qualified Items: $($qualifiedWorkItems -join ', ')"
                Write-Host "Commits to cherry-pick: $($cherryPickCommits -join ', ')"

                # Step 3: Prepare release branch
                Write-Host "##[section]🔧 Creating/updating branch ${releaseBranch}"
                git config --global user.email "build@azure.dev"
                git config --global user.name "Azure DevOps"

                git fetch origin
                $branchExists = git ls-remote --heads origin $releaseBranch

                if ($branchExists) {
                  Write-Host "📦 Branch exists – checking out"
                  git checkout $releaseBranch
                  git pull origin $releaseBranch
                } else {
                  Write-Host "🌱 Creating new branch from main"
                  git checkout main
                  git pull origin main
                  git checkout -b $releaseBranch
                }

                # Step 4: Cherry-pick commits
                foreach ($commit in $cherryPickCommits) {
                  try {
                    Write-Host "🔄 Cherry-picking $commit"
                    git cherry-pick $commit
                  } catch {
                    Write-Host "⚠️ Cherry-pick failed for $commit; aborting and skipping"
                    git cherry-pick --abort
                  }
                }

                # Step 5: Push branch
                Write-Host "##[section]📤 Pushing branch ${releaseBranch}"
                git push origin $releaseBranch

                Write-Host "🎉 Done: branch ${releaseBranch} with cherry-picked commits"
